language: php

php:
    - 5.5

env:
    global:
        - ONIKIRI_SPEC_MYSQL_USER="root" ONIKIRI_SPEC_MYSQL_DATABASE="app"
        - ONIKIRI_SPEC_PGSQL_USER="postgres" ONIKIRI_SPEC_PGSQL_DATABASE="app"
        - SAMURAI_SPEC_REDIS_HOST="localhost"

notifications:
    email:
        - 8823-scholar@hayabusa-lab.jp

branches:
    only:
        - feature/3.0

services:
    - redis-server

install:
    - composer self-update
    - composer install
    - mysql -e 'CREATE DATABASE app'
    - psql -c 'CREATE DATABASE app;' -U postgres
    - wget -O phpredis.tar.gz --no-check-certificate https://github.com/nicolasff/phpredis/tarball/master
    - tar -xzf phpredis.tar.gz
    - sh -c "cd phpredis-phpredis-* && phpize && ./configure && make && sudo make install"
    - phpenv config-add .travis/php.ini

script:
    - Samurai/Console/app spec

after_script:
    - travis_retry php vendor/bin/coveralls -v

cache:
    directories:
        - vendor

