language: php

php:
    - 5.4

env:
    global:
        - secure: "IdVGAor1x4rAUIyDZ/3RNkvFKCVarR/YA8QTq4GIL7I+ZlTd7MuzjPG5nBMv+oleXFUrDJQZJhmY8jdeCzhDY5YV94Y27q+ZPkH+s+aAhO/Ebjs3Rs+y1mnxNHKRkDIwvOwtsydwFzB64sjBZ4wiIKdfcy/3i18F8WaciF5Z4XU="
        - ONIKIRI_SPEC_MYSQL_USER="root" ONIKIRI_SPEC_MYSQL_DATABASE="app"
        - ONIKIRI_SPEC_PGSQL_USER="postgres" ONIKIRI_SPEC_PGSQL_DATABASE="app"

notifications:
    email:
        - 8823-scholar@hayabusa-lab.jp

branches:
    only:
        - feature/3.0

before_script:
    - composer self-update
    - composer install
    - mysql -e 'CREATE DATABASE app'
    - psql -c 'CREATE DATABASE app;' -U postgres
    - phpenv config-add .travis/php.ini

script:
    - Samurai/Console/app spec

after_script:
    - vendor/bin/coveralls -v

