language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

sudo: false

env:
    global:
        - ONIKIRI_SPEC_MYSQL_USER="root" ONIKIRI_SPEC_MYSQL_DATABASE="app"
        - ONIKIRI_SPEC_PGSQL_USER="postgres" ONIKIRI_SPEC_PGSQL_DATABASE="app"
        - SAMURAI_SPEC_REDIS_HOST="localhost"

notifications:
    email:
        - 8823-scholar@hayabusa-lab.jp

branches:
    only:
        - feature/3.0

services:
    - redis-server

install:
    - mv ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ${HOME}/xdebug.ini || return 0
    - composer self-update
    - travis_retry composer update --no-interaction
    - mysql -e 'CREATE DATABASE app'
    - psql -c 'CREATE DATABASE app;' -U postgres
    - wget -O phpredis.tar.gz --no-check-certificate https://github.com/nicolasff/phpredis/tarball/master
    - tar -xzf phpredis.tar.gz
    - sh -c "cd phpredis-phpredis-* && phpize && ./configure && make && sudo make install"
    - phpenv config-add .travis/php.ini

script:
    - cp ${HOME}/xdebug.ini ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
    - Samurai/Console/app spec
    - mv ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ${HOME}/xdebug.ini || return 0

after_success:
    - travis_retry php vendor/bin/coveralls -v

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

