language: php

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: hhvm
        - php: nightly

env:
    global:
        - ONIKIRI_SPEC_MYSQL_USER="root" ONIKIRI_SPEC_MYSQL_DATABASE="app"
        - ONIKIRI_SPEC_PGSQL_USER="postgres" ONIKIRI_SPEC_PGSQL_DATABASE="app"
        - SAMURAI_SPEC_REDIS_HOST="localhost"

notifications:
    email:
        - 8823-scholar@hayabusa-lab.jp

branches:
    only:
        - feature/3.0

services:
    - redis-server

before_install:
    - mv ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ${HOME}/xdebug.ini || return 0

install:
    - travis_retry composer install --dev --no-interaction --prefer-source
    - mysql -e 'CREATE DATABASE app'
    - psql -c 'CREATE DATABASE app;' -U postgres
    - mkdir -p ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d
    - phpenv config-add .travis/php.ini

script:
    - cp ${HOME}/xdebug.ini ${HOME}/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini || return 0
    - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then rm phpspec.yml; fi;'
    - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then mv phpspec.hhvm.yml phpspec.yml; fi;'
    - ./src/Console/app spec

after_success:
    - travis_retry php vendor/bin/coveralls -v

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

